name = "avat365"
main = "src/index.js"
compatibility_date = "2026-09-16"

[[containers]]
max_instances = 1
class_name = "DjangoContainer"
image = "./Dockerfile"

[[durable_objects.bindings]]
name = "DJANGO_CONTAINER"
class_name = "DjangoContainer"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["DjangoContainer"]

[vars]
DJANGO_ALLOWED_HOSTS = "avat365.workers.dev"
