# Generated by Django 5.2.17 on 2026-09-15 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='Описание')),
                ('file', models.FileField(blank=True, help_text='Если файл не загружен — вместо «Смотреть/Скачать» покажется кнопка «Запросить документы» (WhatsApp)', null=True, upload_to='documents/', verbose_name='Файл (PDF)')),
                ('size_label', models.CharField(blank=True, help_text='Например «PDF · 8 МБ». Если пусто — посчитается автоматически по загруженному файлу.', max_length=30, verbose_name='Подпись размера')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок показа')),
                ('is_published', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы проекта',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FAQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200, verbose_name='Вопрос')),
                ('answer', models.TextField(verbose_name='Ответ')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок показа')),
                ('is_published', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
            ],
            options={
                'verbose_name': 'Вопрос FAQ',
                'verbose_name_plural': 'FAQ',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(choices=[('apartment', 'Апартаменты'), ('cottage', 'Коттедж')], max_length=16, verbose_name='Тип')),
                ('slug', models.SlugField(help_text='Используется в адресе страницы, например cottage-77', max_length=80, unique=True)),
                ('area_sqm', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Площадь, м²')),
                ('bedrooms', models.PositiveSmallIntegerField(verbose_name='Спален')),
                ('bathrooms', models.PositiveSmallIntegerField(verbose_name='Санузлов')),
                ('room_summary', models.CharField(blank=True, help_text='Например «кухня-гостиная» — если пусто, будет показано «N спальни · N санузла»', max_length=120)),
                ('floor_plan_image', models.ImageField(upload_to='properties/plans/', verbose_name='Изображение планировки')),
                ('description', models.TextField(blank=True, verbose_name='Описание для детальной страницы')),
                ('whatsapp_message', models.CharField(blank=True, help_text='Если пусто — сформируется автоматически из типа и площади', max_length=300)),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок показа')),
                ('is_published', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
            ],
            options={
                'verbose_name': 'Планировка',
                'verbose_name_plural': 'Планировки',
                'ordering': ['property_type', 'order', 'area_sqm'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(default='+996222170399', help_text='Формат: +996222170399 (используется для ссылок tel:)', max_length=32)),
                ('whatsapp_number', models.CharField(default='996222170399', help_text='Только цифры, без + и пробелов (используется для ссылок wa.me)', max_length=32)),
            ],
            options={
                'verbose_name': 'Контакты сайта',
                'verbose_name_plural': 'Контакты сайта',
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='properties/gallery/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='catalog.property')),
            ],
            options={
                'verbose_name': 'Фото планировки',
                'verbose_name_plural': 'Фото планировки (галерея)',
                'ordering': ['order'],
            },
        ),
    ]
