# Generated by Django 5.2.17 on 2026-09-17 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=32, verbose_name='Телефон (WhatsApp)')),
                ('property_type', models.CharField(choices=[('apartment', 'Апартаменты'), ('cottage', 'Коттедж')], max_length=16, verbose_name='Интересует')),
                ('source_page', models.CharField(blank=True, help_text='Страница, с которой отправлена заявка', max_length=200, verbose_name='Источник')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата заявки')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Обработана')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='property',
            name='amenities',
            field=models.CharField(blank=True, help_text='Через запятую, например: Терраса, Парковка, Кладовая', max_length=300, verbose_name='Удобства'),
        ),
        migrations.AddField(
            model_name='property',
            name='location',
            field=models.CharField(blank=True, default='Кыргызстан, Иссык-Куль, с. Чон-Сары-Ой', max_length=200, verbose_name='Адрес/локация'),
        ),
        migrations.AddField(
            model_name='property',
            name='price',
            field=models.CharField(blank=True, help_text='Например «от $45 000» или «По запросу» — если пусто, цена не показывается', max_length=60, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='property',
            name='video',
            field=models.FileField(blank=True, help_text='Необязательно — короткий видео-обзор для галереи на детальной странице', null=True, upload_to='properties/video/', verbose_name='Видео (mp4)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='address',
            field=models.CharField(blank=True, default='Токтогула 147, кабинет 40', max_length=200, verbose_name='Адрес офиса'),
        ),
    ]
