# Generated by Django 5.2.17 on 2026-09-18 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_lead_property_amenities_property_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='apartments_hero_image',
            field=models.ImageField(blank=True, help_text='Показывается на странице /apartments/ вместо общего фона. Широкое изображение, как баннер.', null=True, upload_to='site/', verbose_name='Фон первого экрана — Апартаменты'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cottages_hero_image',
            field=models.ImageField(blank=True, help_text='Показывается на странице /cottages/ вместо общего фона. Широкое изображение, как баннер.', null=True, upload_to='site/', verbose_name='Фон первого экрана — Коттеджи'),
        ),
    ]
