# Generated by Django 5.2.17 on 2026-09-23 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_sitesettings_apartments_hero_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='about_us_photo',
            field=models.ImageField(blank=True, help_text='Страница «О компании». Фото справа от видео.', null=True, upload_to='site/about-us/', verbose_name='О компании — фото (правый блок)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_us_video',
            field=models.FileField(blank=True, help_text='Страница «О компании». Видео без звука, зацикленное, слева от фото. Формат MP4.', null=True, upload_to='site/about-us/', verbose_name='О компании — видео (левый блок)'),
        ),
    ]
