# Generated by Django 5.2.17 on 2026-09-23 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_sitesettings_about_us_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='about_us_experience_photo',
            field=models.ImageField(blank=True, help_text='Страница «О компании», блок «Опыт, который можно увидеть» — большая тёмная карточка с кнопкой «Получить презентацию».', null=True, upload_to='site/about-us/', verbose_name='4. Фото в карточке «Познакомьтесь с AVAT 365»'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_us_mission_video',
            field=models.FileField(blank=True, help_text='Страница «О компании». Видео без звука, зацикленное, на фоне текста миссии и видения.', null=True, upload_to='site/about-us/', verbose_name='3. Видео в блоке «Наша миссия / Наше видение»'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_us_ticker_photo_1',
            field=models.ImageField(blank=True, help_text='Страница «О компании», блок «Опыт, который можно увидеть» — узкая карточка со скроллящимися фото справа внизу.', null=True, upload_to='site/about-us/', verbose_name='6. Лента «Нам доверяют» — фото 1 из 5'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_us_ticker_photo_2',
            field=models.ImageField(blank=True, null=True, upload_to='site/about-us/', verbose_name='7. Лента «Нам доверяют» — фото 2 из 5'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_us_ticker_photo_3',
            field=models.ImageField(blank=True, null=True, upload_to='site/about-us/', verbose_name='8. Лента «Нам доверяют» — фото 3 из 5'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_us_ticker_photo_4',
            field=models.ImageField(blank=True, null=True, upload_to='site/about-us/', verbose_name='9. Лента «Нам доверяют» — фото 4 из 5'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_us_ticker_photo_5',
            field=models.ImageField(blank=True, null=True, upload_to='site/about-us/', verbose_name='10. Лента «Нам доверяют» — фото 5 из 5'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_us_trust_photo',
            field=models.ImageField(blank=True, help_text='Страница «О компании», блок «Опыт, который можно увидеть» — карточка с портретом человека и текстом на английском.', null=True, upload_to='site/about-us/', verbose_name='5. Фото в карточке с портретом (справа в блоке «Опыт»)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='about_us_photo',
            field=models.ImageField(blank=True, help_text='Страница «О компании», тот же блок вверху страницы, фото рядом с видео.', null=True, upload_to='site/about-us/', verbose_name='2. Фото в самом верху (справа)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='about_us_video',
            field=models.FileField(blank=True, help_text='Страница «О компании», блок «AVAT Construction строит уже 15 лет». Видео без звука, зацикленное. Формат MP4.', null=True, upload_to='site/about-us/', verbose_name='1. Видео в самом верху (слева)'),
        ),
    ]
